dist: xenial
sudo: required
language: java

env:
  global:
    - SONATYPE_USERNAME=ph@phloc.com
    - secure: "CUjRaSEJHFeNNDc3fUNXWqh/lorDYEZbGSOHLhHaCyIU8L19CsjBFOuX64FVbY5b9L2EHTWlhhl9TKjrx0djYw1Wl
HrMSWQTFeuwt0WbDrRDJz9lbQ9oAOKWJA51UjmdzOfaUkM6P+Qj7TeLn0khnhD+gR5oTrwnKW+BziH9vqE9v9QRHHzDkTA32cCqh
zC67KzXJq3irl100Z+1LVGRsceRLwat39hIoWE3nzVXQPD/0flsNoP3vyX9+xEByKaeHCfIVc1AtQRgTS6x6Oj8W7GXPJU3fX96D
hIwGyLfVp/j0TAT7paf0UlKiaaO3WNfV13ufSo8xrNnB6CgtBC8gJQeImBpKBUWXY6KFcTQRxC5tViohdXWjmTEA1/0FqpGLmVnh
5HoSkzpkNTHlooTQI9Ho31ApCbvAAbYILLJtvjIu4VZAMg5S3qtDYVL/N3q9MKMPP5zqj3j/tQnp5EtRwl1K4oo3+EU35+b8FPZt
gHj45GymtCal7y0v9oaFMJNJoel+STJxA5WITbxUGuXJpirGO1rRG1blhuH3adtNmeTFIWFihrW3DGA2VBdDzne9QC4133UF8BSi
G2FvNR8zpt/M/GUx6CfsYRkDUdoh0rrwMe/qbt2WG+hvDuAAuj2jXJdFvJ3GrX7ALTrThhtxxPpRMEPk7XIKcACO3Ajc9s="  

addons:
  sonarcloud:
    organization: "phax-github"
    token:
      secure: "jikEViFpcJilyTrjO+8oPIZ4hWm64kVuMeFkU09+dyd+j6nvU+Q4V2YaQ2An+6wE3D/4ohgBEPqQGDILwb0mxORmLsUn56Z0NsqS37x9Y8mSaAbD0tuCeT0rGdQHeQy59f512USwELB0yhrChbcFe
wws8xTlnu1hbOSAj9rQGW4y3RQOAFM4UBS1lw+DzIGfkEnShbLozOPAAHbM3/Uv2o1WooCmaiD4bHmd3kAi81HMf+wKd597MWHSiBobxRjoZRr4okCw1hGgudWIxIDGGQb7Wpp76S6iJ8RE+7cXsNdtsZjNReTEN
NguCyJQmg8ygIrE8jLhHCu1cOVFpmhDqSv/wEbWVp0ienGFZqWos2J+DhKHK0fpfAqtbujixYDnSwSJGiM+U/4mYFgzAiTF2kKJR1+FxjUBPzxlrESG+XnlwAKnNp9atYrYyNMv8mz/aiQoWYNbk8SZcFsb1cKFG
KzDVImxOMXThyWumY1uTS4dYC6l2+vXWj9WFaGL6k7RGmbQjC4qZoMdgASJ36IBz+C4XbeZHQ7pj7As2LcRIGeJ5qe8FLouH24Qsky7fMu4TfAR7+kodECI4KKIjBZ8LThM4MXlHxm/9PcTdJM76ueh9uyFkn0SA
SMCAu6E9WCOzRraYOrVYh2TjBGX2RHgzg8c1/AY6Bh1ppj7w6jR1xc="

install:
#  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U -P jdeps
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U
  
cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - master

jobs:
  include:
    - stage: test
      jdk: openjdk8
      script:
        - mvn test -B -P coverage sonar:sonar
      after_success:
        - mvn deploy --settings travis-settings.xml -DskipTests=true -B -P travis-deploy
        - bash <(curl -s https://codecov.io/bash)
    - stage: test
      jdk: openjdk11
      script:
        - mvn test -B
    - stage: test
      jdk: openjdk14
      script:
        - mvn test -B
